<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

return new class extends Migration
{
    public function up(): void
    {
        if (DB::getDriverName() !== 'pgsql') {
            throw new RuntimeException('Platform delivery primitives require PostgreSQL.');
        }
        DB::unprepared(<<<'SQL'
            CREATE DOMAIN platform_ulid AS char(26) CHECK (VALUE ~ '^[0-7][0-9A-HJKMNP-TV-Z]{25}$');
            CREATE DOMAIN platform_hash AS char(64) CHECK (VALUE ~ '^[a-f0-9]{64}$');
            CREATE TABLE platform_technical_operations (
                id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                public_id platform_ulid NOT NULL UNIQUE,
                correlation_id platform_ulid NOT NULL,
                created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
            );
            CREATE TABLE platform_idempotency_keys (
                id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                public_id platform_ulid NOT NULL UNIQUE,
                scope_hash platform_hash NOT NULL,
                actor_hash platform_hash NOT NULL,
                key_hash platform_hash NOT NULL,
                request_hash platform_hash NOT NULL,
                state varchar(16) NOT NULL CHECK (state IN ('processing','completed')),
                response_ref platform_ulid,
                expires_at timestamptz NOT NULL,
                created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
                UNIQUE (scope_hash, actor_hash, key_hash),
                CHECK ((state = 'processing' AND response_ref IS NULL) OR (state = 'completed' AND response_ref IS NOT NULL))
            );
            CREATE INDEX platform_idempotency_expiry_idx ON platform_idempotency_keys (expires_at);
            CREATE TABLE platform_outbox_messages (
                id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                event_id platform_ulid NOT NULL UNIQUE,
                event_name varchar(100) NOT NULL,
                version smallint NOT NULL CHECK (version > 0),
                aggregate_type varchar(64) NOT NULL,
                aggregate_id platform_ulid NOT NULL,
                correlation_id platform_ulid NOT NULL,
                occurred_at timestamptz NOT NULL,
                recorded_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
                content_ciphertext text NOT NULL,
                content_hash platform_hash NOT NULL,
                status varchar(16) NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','published')),
                attempts integer NOT NULL DEFAULT 0 CHECK (attempts >= 0),
                next_attempt_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
                published_at timestamptz,
                last_error_code varchar(64),
                CHECK ((status = 'pending' AND published_at IS NULL) OR (status = 'published' AND published_at IS NOT NULL))
            );
            CREATE INDEX platform_outbox_pending_idx ON platform_outbox_messages(status, next_attempt_at, id);
            CREATE INDEX platform_outbox_aggregate_idx ON platform_outbox_messages(aggregate_type, aggregate_id);
            CREATE INDEX platform_outbox_correlation_idx ON platform_outbox_messages(correlation_id);
            CREATE TABLE platform_inbox_messages (
                id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                event_id platform_ulid NOT NULL UNIQUE,
                source varchar(64) NOT NULL,
                message_id platform_ulid NOT NULL,
                content_hash platform_hash NOT NULL,
                correlation_id platform_ulid NOT NULL,
                processed_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
                UNIQUE (source, message_id)
            );
            CREATE TABLE platform_technical_effects (
                id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                public_id platform_ulid NOT NULL UNIQUE,
                event_id platform_ulid NOT NULL UNIQUE REFERENCES platform_inbox_messages(event_id),
                operation_id platform_ulid NOT NULL REFERENCES platform_technical_operations(public_id),
                correlation_id platform_ulid NOT NULL,
                created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
            );
            CREATE FUNCTION platform_outbox_immutable() RETURNS trigger LANGUAGE plpgsql AS $$
            BEGIN
                IF TG_OP = 'DELETE' THEN
                    RAISE EXCEPTION 'Outbox content is immutable' USING ERRCODE = '23514';
                END IF;
                IF (to_jsonb(NEW) - ARRAY['status','attempts','next_attempt_at','published_at','last_error_code'])
                    IS DISTINCT FROM
                    (to_jsonb(OLD) - ARRAY['status','attempts','next_attempt_at','published_at','last_error_code']) THEN
                    RAISE EXCEPTION 'Outbox content is immutable' USING ERRCODE = '23514';
                END IF;
                RETURN NEW;
            END $$;
            CREATE TRIGGER platform_outbox_immutable_trigger BEFORE UPDATE OR DELETE ON platform_outbox_messages
                FOR EACH ROW EXECUTE FUNCTION platform_outbox_immutable();
            SQL);
    }

    public function down(): void
    {
        DB::unprepared(<<<'SQL'
            DROP TABLE IF EXISTS platform_technical_effects;
            DROP TABLE IF EXISTS platform_inbox_messages;
            DROP TABLE IF EXISTS platform_outbox_messages;
            DROP FUNCTION IF EXISTS platform_outbox_immutable();
            DROP TABLE IF EXISTS platform_idempotency_keys;
            DROP TABLE IF EXISTS platform_technical_operations;
            DROP DOMAIN IF EXISTS platform_ulid;
            DROP DOMAIN IF EXISTS platform_hash;
            SQL);
    }
};
